spring.application.name=Pets

# Render 会通过 PORT 环境变量指定端口
server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://ep-hidden-frog-a1yb23wc-pooler.ap-southeast-1.aws.neon.tech:5432/neondb}
spring.datasource.username=${DATABASE_USERNAME:neondb_owner}
spring.datasource.password=${DATABASE_PASSWORD:npg_P3kxqru9vGDV}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000

mybatis.mapper-locations=classpath:mapper/**/*.xml

mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.default-enum-type-handler=org.apache.ibatis.type.EnumOrdinalTypeHandler
logging.level.com.tox.tox.pets.mapper=DEBUG

spring.data.redis.host=${REDIS_HOST:first-ghost-85679.upstash.io}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:gQAAAAAAAU6vAAIncDI5NzhmM2QwOWYxY2E0ODBlOTQ2ZWI5OTkzNWJmNDQ5MnAyODU2Nzk}
spring.data.redis.ssl.enabled=${REDIS_SSL:true}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:tox-pets}
cloudinary.api-key=${CLOUDINARY_API_KEY:343874219974122}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:sgezsasJo08rJNXrog_PVZF1mrM}

# HikariCP Connection Pool Settings to prevent stale connections
# Max lifetime of a connection in the pool (10 minutes).
# This should be shorter than any database or network infrastructure timeout.
spring.datasource.hikari.max-lifetime=600000
# Time a connection can be idle before being retired (5 minutes).
spring.datasource.hikari.idle-timeout=300000
# Keepalive time to prevent connections from being closed by the network (1 minute).
spring.datasource.hikari.keepalive-time=60000
# A simple query to test the validity of the connection.
spring.datasource.hikari.connection-test-query=SELECT 1

# Apifox / OpenAPI Config
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true

springdoc.group-configs[0].group='pets-api'
springdoc.group-configs[0].packages-to-scan=com.tox.tox.pets.controller